### ISSUE TITLE
Push Latest Code To Heroku and Test

### ISSUE THREAD

**Issue by wryanj** [Kyle7286/Divvy#127]

**Comment by Kyle7286** [comment]
Issues on heroku site:

![image](https://user-images.githubusercontent.com/74633494/119284319-6fba2900-bc0d-11eb-9ff8-23a7ae35fe2e.png)

**Comment by Kyle7286** [comment]
Issue was that in server.js, app.use(routes) was above the app.use(state...) block of code.
Moving it down below fixed the issue.
